USE DEVA;

#COUNT VALUES
SELECT COUNT(*)
FROM ZEPTO;

#DATA
SELECT *
FROM ZEPTO;

#NULL VALUES
SELECT *
FROM ZEPTO
WHERE 
Z_ID IS NULL 
OR CATEGORY IS NULL
OR NAME IS NULL
OR MRP IS NULL
OR DISCOUNTPERCENT IS NULL
OR AVAILABLEQUANTITY IS NULL 
OR DISCOUNTEDSELLINGPRICE IS NULL
OR WEIGHTINGMS IS NULL
OR OUTOFSTOCK IS NULL
OR QUANTITY IS NULL;

#PRODUCT CATEGORIES
SELECT DISTINCT CATEGORY
FROM ZEPTO;

#PRODUCT IN STOCK VS OUT OF STOCK
SELECT OUTOFSTOCK , COUNT(Z_ID) AS COUNTS
FROM ZEPTO
GROUP BY OUTOFSTOCK;

#PRODUCT NAME PRESENT IN MULTIPLE TIMES
SELECT NAME,COUNT(Z_ID) AS COUNT
FROM ZEPTO
GROUP BY NAME 
HAVING COUNT > 1
ORDER BY COUNT DESC;

# data cleaning
# product price = 0
SELECT *
FROM ZEPTO
WHERE MRP = 0
OR DISCOUNTEDSELLINGPRICE = 0;

# delete where mrp = 0
DELETE 
FROM ZEPTO
WHERE MRP = 0 
OR DISCOUNTEDSELLINGPRICE = 0;

# convert paise to rupees
UPDATE ZEPTO
SET MRP = MRP/100.0,
DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE/100.0;

SELECT MRP,DISCOUNTEDSELLINGPRICE
FROM ZEPTO;

SELECT * FROM ZEPTO;

#top 10 best-value products based on the discount percentage
SELECT DISTINT NAME,DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT  10;

# High Mrp but out of stock
SELECT DISTINCT NAME,MRP,OUTOFSTOCK
FROM ZEPTO
WHERE OUTOFSTOCK = "TRUE"
ORDER BY MRP DESC;

#estimated revenue for each category

SELECT CATEGORY,
SUM(MRP * QUANTITY) AS ESTIMATED_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY ESTIMATED_REVENUE DESC;

# MRP GRAETER THAN 500 AND DISCOUNT IS LESS THAN 10
SELECT *
FROM ZEPTO
WHERE MRP > 500
AND DISCOUNTPERCENT < 10;

#TOP 5 CATEGORIES OFFERING HIGHEST AVERAGE DISCOUNT PERCENT
SELECT CATEGORY,AVG(DISCOUNTPERCENT) AS AVG_OF_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVG_OF_DISCOUNT 
DESC
LIMIT 5;

# PRICE PER GRAM FOR PRODUCTS ABOVE 100 GRAM AND SORT BY BEST values
SELECT DISTINCT NAME,WEIGHTINGMS,DISCOUNTEDSELLINGPRICE,
ROUND (DISCOUNTEDSELLINGPRICE / WEIGHTINGMS,2) AS PRICE_PER_GRAM
FROM ZEPTO 
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GRAM ;

SELECT DISTINCT NAME,WEIGHTINGMS,
CASE
WHEN WEIGHTINGMS < 1000 THEN "LOW"
WHEN WEIGHTINGMS < 5000 THEN "MEDIUM"
ELSE "BULK"
END AS WEIGHT_CATEGORY
FROM ZEPTO;

SELECT CATEGORY,
SUM(WEIGHTINGMS * AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;
